#!/usr/bin/env node

import { execSync } from "node:child_process";
import { randomBytes } from "node:crypto";
import { existsSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { createInterface } from "node:readline";
import { chdir } from "node:process";

/**
 * Get the project root directory (where package.json and drizzle.config.ts are located)
 */
function getProjectRoot(): string {
	// Get the directory where this script is located
	const scriptDir = dirname(fileURLToPath(import.meta.url));
	// The project root is one level up from the scripts directory
	const projectRoot = resolve(scriptDir, "..");

	// Verify we found the right directory
	if (!existsSync(join(projectRoot, "package.json"))) {
		throw new Error(
			`Could not find package.json in ${projectRoot}. Are you running this from the project root?`,
		);
	}

	if (!existsSync(join(projectRoot, "drizzle.config.ts"))) {
		throw new Error(
			`Could not find drizzle.config.ts in ${projectRoot}. Are you running this from the project root?`,
		);
	}

	return projectRoot;
}

/**
 * Check Node.js version
 */
function checkNodeVersion(): void {
	const nodeVersion = process.version;
	const majorVersion = parseInt(nodeVersion.slice(1).split(".")[0] || "0", 10);

	if (majorVersion < 24) {
		console.error(
			`❌ Error: Node.js version 24 or higher is required. Current version: ${nodeVersion}`,
		);
		console.error("Please upgrade Node.js and try again.");
		process.exit(1);
	}
}

/**
 * Prompt user for confirmation
 */
function promptConfirmation(): Promise<boolean> {
	const rl = createInterface({
		input: process.stdin,
		output: process.stdout,
	});

	return new Promise((resolve) => {
		rl.question(
			"\n⚠️  WARNING: This will reset/initialize the project and remove:\n" +
				"   - Existing .env file\n" +
				"   - Existing database (db.sqlite)\n" +
				"   - Any existing security keys\n\n" +
				"Do you want to continue? (yes/no): ",
			(answer) => {
				rl.close();
				resolve(answer.toLowerCase() === "yes" || answer.toLowerCase() === "y");
			},
		);
	});
}


/**
 * Generate a secure JWT secret
 */
function generateJWTSecret(): string {
	// Generate 32 random bytes and convert to base64
	// Base64 encoding gives us ~44 characters, which exceeds the 32-character minimum
	const secret = randomBytes(32).toString("base64");
	return secret;
}

/**
 * Extract hostname from URL for RP_ID
 */
function extractHostname(url: string): string {
	try {
		const urlObj = new URL(url);
		return urlObj.hostname;
	} catch {
		throw new Error(`Invalid URL format: ${url}`);
	}
}

/**
 * Remove existing files if they exist
 */
function removeExistingFiles(projectRoot: string): void {
	const filesToRemove = [".env", "db.sqlite", "db.sqlite-journal"];

	for (const file of filesToRemove) {
		const filePath = join(projectRoot, file);
		if (existsSync(filePath)) {
			try {
				rmSync(filePath, { force: true });
				console.log(`✓ Removed ${file}`);
			} catch (error) {
				console.warn(`⚠️  Warning: Could not remove ${file}:`, error);
			}
		}
	}
}

/**
 * Create .env file with required configuration
 */
function createEnvFile(projectRoot: string): void {
	const jwtSecret = generateJWTSecret();
	const siteUrl = "http://localhost:3100";
	const siteName = "Passwordless Demo";
	const databaseUrl = "./db.sqlite";
	const nodeEnv = "development";
	const rpId = extractHostname(siteUrl);

	const envContent = `# Generated by setup script
# DO NOT commit this file to version control

JWT_SECRET=${jwtSecret}
SITE_URL=${siteUrl}
SITE_NAME=${siteName}
RP_ID=${rpId}
DATABASE_URL=${databaseUrl}
NODE_ENV=${nodeEnv}
`;

	const envPath = join(projectRoot, ".env");
	writeFileSync(envPath, envContent, "utf-8");
	console.log("✓ Created .env file with configuration");
}

/**
 * Check if better-sqlite3 native bindings are available
 */
function checkBetterSqlite3Bindings(projectRoot: string): boolean {
	// Check for better-sqlite3 bindings in common locations
	const possiblePaths = [
		join(
			projectRoot,
			"node_modules/.pnpm/better-sqlite3@12.6.2/node_modules/better-sqlite3/build/Release/better_sqlite3.node",
		),
		join(
			projectRoot,
			"node_modules/.pnpm/better-sqlite3@12.6.2/node_modules/better-sqlite3/build/better_sqlite3.node",
		),
		join(
			projectRoot,
			"node_modules/better-sqlite3/build/Release/better_sqlite3.node",
		),
		join(projectRoot, "node_modules/better-sqlite3/build/better_sqlite3.node"),
	];

	return possiblePaths.some((path) => existsSync(path));
}

/**
 * Ensure dependencies are installed
 */
function ensureDependencies(projectRoot: string): void {
	// Check if node_modules exists
	if (!existsSync(join(projectRoot, "node_modules"))) {
		try {
			console.log("📦 Installing dependencies...");
			execSync("pnpm install", {
				stdio: "inherit",
				cwd: projectRoot,
			});
			console.log("✓ Dependencies installed");
		} catch (error) {
			console.error(
				"❌ Error installing dependencies. Please run 'pnpm install' manually.",
			);
			throw error;
		}
	} else {
		console.log("✓ Dependencies already installed");
	}

	// Check if better-sqlite3 bindings are available
	if (!checkBetterSqlite3Bindings(projectRoot)) {
		console.error("\n");
		console.error(
			"\x1b[31m❌ ERROR: better-sqlite3 native module bindings are missing.\x1b[0m",
		);
		console.error(
			"\x1b[31m   This usually means pnpm has blocked the build scripts.\x1b[0m",
		);
		console.error("\n");
		console.error(
			"\x1b[31m   Please run the following command to approve build scripts:\x1b[0m",
		);
		console.error("\x1b[31m   pnpm approve-builds\x1b[0m");
		console.error("\n");
		console.error(
			"\x1b[31m   Then approve 'better-sqlite3' when prompted.\x1b[0m",
		);
		console.error(
			"\x1b[31m   After that, run this setup script again.\x1b[0m",
		);
		console.error("\n");
		process.exit(1);
	}

	console.log("✓ better-sqlite3 native module is available");
}

/**
 * Initialize database using drizzle-kit push
 */
function initializeDatabase(projectRoot: string): void {
	console.log("\n📦 Initializing database schema...");

	// Verify we're in the right directory (should have drizzle.config.ts)
	const drizzleConfigPath = join(projectRoot, "drizzle.config.ts");
	if (!existsSync(drizzleConfigPath)) {
		throw new Error(
			`drizzle.config.ts not found at ${drizzleConfigPath}. Are you running this from the project root?`,
		);
	}

	try {
		execSync("pnpm db:push", {
			stdio: "inherit",
			cwd: projectRoot,
			env: process.env,
		});
		console.log("✓ Database initialized successfully");
	} catch (error: any) {
		console.error("\n❌ Error initializing database");
		if (
			error?.message?.includes("bindings") ||
			error?.message?.includes("better-sqlite3")
		) {
			console.error(
				"  The better-sqlite3 native module needs to be rebuilt.",
			);
			console.error("  Try running: pnpm install --force better-sqlite3");
			console.error("  Then run the setup script again.");
		}
		throw error;
	}
}

/**
 * Main setup function
 */
async function main(): Promise<void> {
	console.log("🚀 Passwordless Demo Database Setup");
	console.log("====================================\n");

	// Get and change to project root directory
	const projectRoot = getProjectRoot();
	console.log(`📁 Project root: ${projectRoot}\n`);
	chdir(projectRoot);

	// Check Node.js version
	checkNodeVersion();
	console.log(`✓ Node.js version check passed (${process.version})\n`);

	// Prompt for confirmation
	const confirmed = await promptConfirmation();
	if (!confirmed) {
		console.log("\n❌ Setup cancelled by user");
		process.exit(0);
	}

	console.log("\n🔄 Starting setup...\n");

	// Ensure dependencies are installed and native modules are built
	ensureDependencies(projectRoot);

	// Remove existing files (.env, database, etc.)
	removeExistingFiles(projectRoot);

	// Create .env file with fresh configuration
	createEnvFile(projectRoot);

	// Initialize database
	initializeDatabase(projectRoot);

	// Success message
	console.log("\n✅ Setup completed successfully!");
	console.log("\nNext steps:");
	console.log("  1. Review the .env file if you need to customize settings");
	console.log("  2. Run 'pnpm dev' to start the development server");
	console.log("  3. Visit http://localhost:3100 in your browser\n");
}

// Run setup
main().catch((error) => {
	console.error("\n❌ Setup failed:", error);
	process.exit(1);
});
