/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRequestCodeRouteImport } from './routes/login-request-code'
import { Route as LoginPasskeyRouteImport } from './routes/login-passkey'
import { Route as LoginAccountPasskeyRouteImport } from './routes/login-account-passkey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupSignupTokenRouteImport } from './routes/signup.$signupToken'
import { Route as LoginViaCodeCodeVerificationTokenRouteImport } from './routes/login-via-code.$codeVerificationToken'
import { Route as ApiOtpLatestRouteImport } from './routes/api/otp-latest'
import { Route as AuthedUserSettingsRouteImport } from './routes/_authed/user-settings'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRequestCodeRoute = LoginRequestCodeRouteImport.update({
  id: '/login-request-code',
  path: '/login-request-code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasskeyRoute = LoginPasskeyRouteImport.update({
  id: '/login-passkey',
  path: '/login-passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginAccountPasskeyRoute = LoginAccountPasskeyRouteImport.update({
  id: '/login-account-passkey',
  path: '/login-account-passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSignupTokenRoute = SignupSignupTokenRouteImport.update({
  id: '/$signupToken',
  path: '/$signupToken',
  getParentRoute: () => SignupRoute,
} as any)
const LoginViaCodeCodeVerificationTokenRoute =
  LoginViaCodeCodeVerificationTokenRouteImport.update({
    id: '/login-via-code/$codeVerificationToken',
    path: '/login-via-code/$codeVerificationToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiOtpLatestRoute = ApiOtpLatestRouteImport.update({
  id: '/api/otp-latest',
  path: '/api/otp-latest',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedUserSettingsRoute = AuthedUserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-account-passkey': typeof LoginAccountPasskeyRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-request-code': typeof LoginRequestCodeRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/user-settings': typeof AuthedUserSettingsRoute
  '/api/otp-latest': typeof ApiOtpLatestRoute
  '/login-via-code/$codeVerificationToken': typeof LoginViaCodeCodeVerificationTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-account-passkey': typeof LoginAccountPasskeyRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-request-code': typeof LoginRequestCodeRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/user-settings': typeof AuthedUserSettingsRoute
  '/api/otp-latest': typeof ApiOtpLatestRoute
  '/login-via-code/$codeVerificationToken': typeof LoginViaCodeCodeVerificationTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/login-account-passkey': typeof LoginAccountPasskeyRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-request-code': typeof LoginRequestCodeRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/_authed/user-settings': typeof AuthedUserSettingsRoute
  '/api/otp-latest': typeof ApiOtpLatestRoute
  '/login-via-code/$codeVerificationToken': typeof LoginViaCodeCodeVerificationTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login-account-passkey'
    | '/login-passkey'
    | '/login-request-code'
    | '/logout'
    | '/signup'
    | '/user-settings'
    | '/api/otp-latest'
    | '/login-via-code/$codeVerificationToken'
    | '/signup/$signupToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login-account-passkey'
    | '/login-passkey'
    | '/login-request-code'
    | '/logout'
    | '/signup'
    | '/user-settings'
    | '/api/otp-latest'
    | '/login-via-code/$codeVerificationToken'
    | '/signup/$signupToken'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/login'
    | '/login-account-passkey'
    | '/login-passkey'
    | '/login-request-code'
    | '/logout'
    | '/signup'
    | '/_authed/user-settings'
    | '/api/otp-latest'
    | '/login-via-code/$codeVerificationToken'
    | '/signup/$signupToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
  LoginAccountPasskeyRoute: typeof LoginAccountPasskeyRoute
  LoginPasskeyRoute: typeof LoginPasskeyRoute
  LoginRequestCodeRoute: typeof LoginRequestCodeRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRouteWithChildren
  ApiOtpLatestRoute: typeof ApiOtpLatestRoute
  LoginViaCodeCodeVerificationTokenRoute: typeof LoginViaCodeCodeVerificationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-request-code': {
      id: '/login-request-code'
      path: '/login-request-code'
      fullPath: '/login-request-code'
      preLoaderRoute: typeof LoginRequestCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-passkey': {
      id: '/login-passkey'
      path: '/login-passkey'
      fullPath: '/login-passkey'
      preLoaderRoute: typeof LoginPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-account-passkey': {
      id: '/login-account-passkey'
      path: '/login-account-passkey'
      fullPath: '/login-account-passkey'
      preLoaderRoute: typeof LoginAccountPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/$signupToken': {
      id: '/signup/$signupToken'
      path: '/$signupToken'
      fullPath: '/signup/$signupToken'
      preLoaderRoute: typeof SignupSignupTokenRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login-via-code/$codeVerificationToken': {
      id: '/login-via-code/$codeVerificationToken'
      path: '/login-via-code/$codeVerificationToken'
      fullPath: '/login-via-code/$codeVerificationToken'
      preLoaderRoute: typeof LoginViaCodeCodeVerificationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/otp-latest': {
      id: '/api/otp-latest'
      path: '/api/otp-latest'
      fullPath: '/api/otp-latest'
      preLoaderRoute: typeof ApiOtpLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/user-settings': {
      id: '/_authed/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof AuthedUserSettingsRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedUserSettingsRoute: typeof AuthedUserSettingsRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedUserSettingsRoute: AuthedUserSettingsRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface SignupRouteChildren {
  SignupSignupTokenRoute: typeof SignupSignupTokenRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSignupTokenRoute: SignupSignupTokenRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
  LoginAccountPasskeyRoute: LoginAccountPasskeyRoute,
  LoginPasskeyRoute: LoginPasskeyRoute,
  LoginRequestCodeRoute: LoginRequestCodeRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRouteWithChildren,
  ApiOtpLatestRoute: ApiOtpLatestRoute,
  LoginViaCodeCodeVerificationTokenRoute:
    LoginViaCodeCodeVerificationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
