/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UserSettingsRouteImport } from './routes/user-settings'
import { Route as TestOtpLatestRouteImport } from './routes/test-otp-latest'
import { Route as TestOtpEventsRouteImport } from './routes/test-otp-events'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LogoutRouteImport } from './routes/logout'
import { Route as LoginRequestCodeRouteImport } from './routes/login-request-code'
import { Route as LoginPasskeyRouteImport } from './routes/login-passkey'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignupSignupTokenRouteImport } from './routes/signup.$signupToken'
import { Route as LoginViaCodeCodeVerificationTokenRouteImport } from './routes/login-via-code.$codeVerificationToken'

const UserSettingsRoute = UserSettingsRouteImport.update({
  id: '/user-settings',
  path: '/user-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TestOtpLatestRoute = TestOtpLatestRouteImport.update({
  id: '/test-otp-latest',
  path: '/test-otp-latest',
  getParentRoute: () => rootRouteImport,
} as any)
const TestOtpEventsRoute = TestOtpEventsRouteImport.update({
  id: '/test-otp-events',
  path: '/test-otp-events',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LogoutRoute = LogoutRouteImport.update({
  id: '/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRequestCodeRoute = LoginRequestCodeRouteImport.update({
  id: '/login-request-code',
  path: '/login-request-code',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginPasskeyRoute = LoginPasskeyRouteImport.update({
  id: '/login-passkey',
  path: '/login-passkey',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupSignupTokenRoute = SignupSignupTokenRouteImport.update({
  id: '/$signupToken',
  path: '/$signupToken',
  getParentRoute: () => SignupRoute,
} as any)
const LoginViaCodeCodeVerificationTokenRoute =
  LoginViaCodeCodeVerificationTokenRouteImport.update({
    id: '/login-via-code/$codeVerificationToken',
    path: '/login-via-code/$codeVerificationToken',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-request-code': typeof LoginRequestCodeRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/test-otp-events': typeof TestOtpEventsRoute
  '/test-otp-latest': typeof TestOtpLatestRoute
  '/user-settings': typeof UserSettingsRoute
  '/login-via-code/$codeVerificationToken': typeof LoginViaCodeCodeVerificationTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-request-code': typeof LoginRequestCodeRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/test-otp-events': typeof TestOtpEventsRoute
  '/test-otp-latest': typeof TestOtpLatestRoute
  '/user-settings': typeof UserSettingsRoute
  '/login-via-code/$codeVerificationToken': typeof LoginViaCodeCodeVerificationTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/login-passkey': typeof LoginPasskeyRoute
  '/login-request-code': typeof LoginRequestCodeRoute
  '/logout': typeof LogoutRoute
  '/signup': typeof SignupRouteWithChildren
  '/test-otp-events': typeof TestOtpEventsRoute
  '/test-otp-latest': typeof TestOtpLatestRoute
  '/user-settings': typeof UserSettingsRoute
  '/login-via-code/$codeVerificationToken': typeof LoginViaCodeCodeVerificationTokenRoute
  '/signup/$signupToken': typeof SignupSignupTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/login-passkey'
    | '/login-request-code'
    | '/logout'
    | '/signup'
    | '/test-otp-events'
    | '/test-otp-latest'
    | '/user-settings'
    | '/login-via-code/$codeVerificationToken'
    | '/signup/$signupToken'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/login-passkey'
    | '/login-request-code'
    | '/logout'
    | '/signup'
    | '/test-otp-events'
    | '/test-otp-latest'
    | '/user-settings'
    | '/login-via-code/$codeVerificationToken'
    | '/signup/$signupToken'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/login-passkey'
    | '/login-request-code'
    | '/logout'
    | '/signup'
    | '/test-otp-events'
    | '/test-otp-latest'
    | '/user-settings'
    | '/login-via-code/$codeVerificationToken'
    | '/signup/$signupToken'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  LoginPasskeyRoute: typeof LoginPasskeyRoute
  LoginRequestCodeRoute: typeof LoginRequestCodeRoute
  LogoutRoute: typeof LogoutRoute
  SignupRoute: typeof SignupRouteWithChildren
  TestOtpEventsRoute: typeof TestOtpEventsRoute
  TestOtpLatestRoute: typeof TestOtpLatestRoute
  UserSettingsRoute: typeof UserSettingsRoute
  LoginViaCodeCodeVerificationTokenRoute: typeof LoginViaCodeCodeVerificationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/user-settings': {
      id: '/user-settings'
      path: '/user-settings'
      fullPath: '/user-settings'
      preLoaderRoute: typeof UserSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-otp-latest': {
      id: '/test-otp-latest'
      path: '/test-otp-latest'
      fullPath: '/test-otp-latest'
      preLoaderRoute: typeof TestOtpLatestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/test-otp-events': {
      id: '/test-otp-events'
      path: '/test-otp-events'
      fullPath: '/test-otp-events'
      preLoaderRoute: typeof TestOtpEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/logout': {
      id: '/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof LogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-request-code': {
      id: '/login-request-code'
      path: '/login-request-code'
      fullPath: '/login-request-code'
      preLoaderRoute: typeof LoginRequestCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login-passkey': {
      id: '/login-passkey'
      path: '/login-passkey'
      fullPath: '/login-passkey'
      preLoaderRoute: typeof LoginPasskeyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup/$signupToken': {
      id: '/signup/$signupToken'
      path: '/$signupToken'
      fullPath: '/signup/$signupToken'
      preLoaderRoute: typeof SignupSignupTokenRouteImport
      parentRoute: typeof SignupRoute
    }
    '/login-via-code/$codeVerificationToken': {
      id: '/login-via-code/$codeVerificationToken'
      path: '/login-via-code/$codeVerificationToken'
      fullPath: '/login-via-code/$codeVerificationToken'
      preLoaderRoute: typeof LoginViaCodeCodeVerificationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SignupRouteChildren {
  SignupSignupTokenRoute: typeof SignupSignupTokenRoute
}

const SignupRouteChildren: SignupRouteChildren = {
  SignupSignupTokenRoute: SignupSignupTokenRoute,
}

const SignupRouteWithChildren =
  SignupRoute._addFileChildren(SignupRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  LoginPasskeyRoute: LoginPasskeyRoute,
  LoginRequestCodeRoute: LoginRequestCodeRoute,
  LogoutRoute: LogoutRoute,
  SignupRoute: SignupRouteWithChildren,
  TestOtpEventsRoute: TestOtpEventsRoute,
  TestOtpLatestRoute: TestOtpLatestRoute,
  UserSettingsRoute: UserSettingsRoute,
  LoginViaCodeCodeVerificationTokenRoute:
    LoginViaCodeCodeVerificationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
